# Use a python base image
FROM python:3.8

# Set the working directory
WORKDIR /app

# Install Python and any additional dependencies if needed
RUN apt-get update && apt-get install -y python3 python3-pip

# Set the working directory
WORKDIR /app

COPY requirements.txt /app

# Install any Python dependencies if required
RUN pip install -r requirements.txt

# Copy de files
COPY src /app/src
COPY files /app/files

# Expose port 9080
EXPOSE 9080

# Run the de server
CMD ["python", "src/GA/server.py"]